### ISSUE TITLE
How the contract works?

### ISSUE THREAD

**Issue by CraigglesO** [feross/bittorrent-protocol#21]
Hey friend. I have a P2P wire protocol question.

I have been building my own implementation. I have been simulating responses from other P2P programs to test and I can’t get passed the handshake. I get a handshake:

bufferSize!: 68
Protocol type: BitTorrent protocol
infoHash: aff8bda8adebdab34e1af9ac648bd93c13ed6344
peerId: 2d4c54313030302d764874743153546a4d583043

Then I try sending a handshake back or a interested or any other code...
Do you have any advice?

Thanks,
Connor.

P.S. - you have something very strange in my mind...
You set the protocol buffer like this: '\u0013BitTorrent protocol'
But that's strange in my mind because it should be \u0019. The string is 19 bits! So how does your implementation even work?! You must be getting the majority of success from ws rather then tcp.

**Comment by CraigglesO** [comment]
Nevermind, you where right! It's \u0013. I don't know why you say you are sending 13 bytes when you are really sending 19. But I am getting responses now and on to the next phase... Seems most torrent software is happiest if you start your next message after handshake with a have message... Otherwise some pretty much just say to screw off.

**Comment by feross** [comment]
0x0013 in hex is 19 in decimal.

Without more information, it's not really possible to guess what's wrong with your program. The best advice I have for you is to run through the test suite for this package and set DEBUG=* so you get the full debug output including every message that is sent. If you make sure your program is sending the same messages in response to a remote peer, then it should work.
