### ISSUE TITLE
Handshake/extended API issue

### ISSUE THREAD

**Issue by astro** [feross/bittorrent-protocol#8]
In `_onHandshake()` we emit the `'handshake'` event where we expect the handler to send with `handshake()` synchronously. If the handler defers handshaking the further body of `_onHandshake()` will send the `extended()` message before the actual protocol `handshake()`, which is a protocol violation.

Is this something you want to get sorted out? A deviation from the current assumptions about callers will probably break API compatibility.

**Comment by feross** [comment]
Yep, confirmed. This issue hasn't affected webtorrent because we always call `handshake()` synchronously in the `'handshake'` event handler. PR welcome.

**Comment by feross** [comment]
Released as 1.5.6.
